### PR TITLE
Css cleanup

### PR DESCRIPTION
**Pull request by bharmon**
HVAC.css: fixing the alignment and height that the sliders go up,
cleaned up HVAC.css code in accordance to Styleguide 1.1

HVAC.css: Cleaned up old modal and text styles for response message style that's been replaced

Makefile: Changed 'dashboard' in 2 places to 'HVAC'.

Signed-off-by: Barbara Harmon bharmon@jaguarlandrover.com

### CODE REVIEW

**Comment by bharmon** [comment]
Hi Art, amcgee7@jaguarlandrover.com, Kelly, kjohnso2@jaguarlandrover.com, and Marco mmorale1@jaguarlandrover.com

We're testing the effectiveness of a Github only review process. Please test this pull request and let me or Aaron know how well it works out for you.

HVAC review: 
1. Doe the makefile work for "make run.feb1"?
2. Do the orange sliders match their backgrounds, and do they go all the way up and down?
3. Is the fan graphic aligned, and does it go all the way up and down? (known issue, the fan graphic doesn't go all the way back to 0)
4. Code cleanup - does hvac.css meet the standards mentioned in Styleguide 1.1?

**Comment by bharmon** [comment]
@amcgee7, @mmorale1, @kjohnso2 

We're testing the effectiveness of a Github only review process. Please test this pull request and let me or Aaron know how well it works out for you.

HVAC review: 
1. Doe the makefile work for "make run.feb1"?
2. Do the orange sliders match their backgrounds, and do they go all the way up and down?
3. Is the fan graphic aligned, and does it go all the way up and down? (known issue, the fan graphic doesn't go all the way back to 0)
4. Code cleanup - does hvac.css meet the standards mentioned in Styleguide 1.1?

**Comment by ghost** [comment]
make run.feb1 works. Climate sliders fills align with backgrounds. Fan graphic aligned to slider. Fan slider slides left and right. CSS code cleanup incorporates Styleguide 1.1 standards. 

OK to merge.

**Comment by ghost** [comment]
:+1:

**Comment by amcgee7** [comment]
Looks good to me.  was able to run HVAC and press all the controls. :+1:

**Pull request merged**
